hotel_admin/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotels.urls')),
]

hotels/urls.py
from django.urls import path

from . import views

app_name = 'hotels'
urlpatterns = [
	# path to enter the index of cities
	path('', views.index, name = 'index'),
	# path to select cities
	path('sel/', views.select_city, name = 'select'),
	# path showing the hotels in the selected city
	path('<str:city_name>/', views.results, name = 'result')
]

hotels/models.py
from django.db import models

class City(models.Model):
	"""
	Stores the cities where the hotels are with a simplified code.
	"""
	name = models.CharField(max_length = 200)
	code = models.CharField(max_length = 50)

	def __str__(self):
		return self.name

class Hotel(models.Model):
	"""
	Stores the hotel pointing to a city with name and code.
	"""
	city = models.ForeignKey(City, on_delete = models.CASCADE)
	name = models.CharField(max_length = 200)
	code = models.CharField(max_length = 50)

	def __str__(self):
		return self.name

hotels/forms.py
from django import forms

from .models import City

class CityForm(forms.Form):
	"""
	A dropdown menu to show the available cities
	"""
	city_names = ((x.name, x.name) for x in City.objects.all())

	city_name = forms.ChoiceField(required = True, choices = city_names)

hotels/views.py
from django.shortcuts import get_object_or_404, render, reverse
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
# from django.template import loader

from .models import City, Hotel
from .forms import CityForm

def index(request):
    """
    Use of generic view to list all cities that are on the database and 
    display it according to hotels/index.html
    """
    form = CityForm()

    context = {
        "form": form,
    }

    return render(request, 'hotels/index.html', context)

def select_city(request):
    """
    Additional view to make the request of the hotels for the selected city.
    """

    form = CityForm(request.POST)
    
    try:
        selected_choice = City.objects.get(name=request.POST['city_name'])
    except City.DoesNotExist:
        return render(request, 'hotels/index.html', {
            'error_message': "The city does not exist.",
            'all_cities' : City.objects.order_by('name'),
            'form' : CityForm(),
        })
    # except KeyError:
    #     # Redisplay the question voting form.
    #     return render(request, 'hotels/index.html', {
    #         'error_message': "You didn't select a choice.",
    #         'all_cities' : City.objects.order_by('name')
    #     })
    else:
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('hotels:result', args=(selected_choice.name,)))


def results(request, city_name):
    """
    Create view that displays the hotels in a city following hotels/results.html
    """
    c = get_object_or_404(City, name = city_name)
    hotels_in_city = Hotel.objects.filter(city__name = city_name)
    context = {
        'hotels_in_city' : hotels_in_city,
        'city_name' : city_name,
    }

    return render(request, 'hotels/result.html', context)

hotels/templates/hotels/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hotel Admin</title>
  </head>
  <body>
    <form action="{% url 'hotels:select' %}" method="post">  
    {% csrf_token %}
    <fieldset>
        <legend><h1>Please choose a city</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {{ form }}
<!--         <input type="text" name="city"> -->
    </fieldset>
    <input type="submit" value="Select">
    </form>
  </body>
</html>

hotels/templates/hotels/result.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hotels in city</title>
  </head>
  <body>
    {% if hotels_in_city %}
        <ul>
        {% for h in hotels_in_city %}
            <li>{{ h.name }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No hotels in {{ city.name }} are available.</p>
    {% endif %}
    <form action="{% url 'hotels:index' %}" method="get">  
<!--     {% csrf_token %} -->
    <input type="submit" value="Back">
    </form>
  </body>
</html>